image: python:3.12
stages:
  - install
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.12"

before_script:
  - apt-get update -y
  - apt-get install -y libpq-dev build-essential python3-dev
  - python3 -m venv venv
  - source venv/bin/activate
  - apt-get update -y
  - apt-get install -y libpq-dev
  - python --version
  - pip install --upgrade pip
  - pip install -v -r scrum-board-visi/requirements.txt

test:
  stage: test
  script:
    - python scrum-board-visi/manage.py test  # Uruchomienie wszystkich testów
  artifacts:
    paths:
      - test-reports/

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - master
