image: python:3.12
stages:
  - install
  - test
  - deploy

variables:
  # Określamy wersję Pythona
  PYTHON_VERSION: "3.12"

before_script:
  # Instalacja potrzebnych narzędzi
  - apt-get update -y
  - apt-get install -y libpq-dev
  - python --version
  - pip install --upgrade pip
  # Przejście do folderu scrum-board-visi, gdzie znajduje się requirements.txt
  - pip install -r scrum-board-visi/requirements.txt

test:
  stage: test
  script:
    - |
      # Ustawienie SQLite na czas testów w pliku settings.py
      sed -i 's|\'ENGINE\':\'django.db.backends.postgresql\'|\'ENGINE\': \'django.db.backends.sqlite3\'|g' scrum-board-visi/settings.py
      # Uruchomienie migracji
      python scrum-board-visi/manage.py makemigrations
      python scrum-board-visi/manage.py migrate
      # Uruchomienie testów
      python scrum-board-visi/manage.py test
  artifacts:
    paths:
      - test-reports/

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - master
