image: python:3.12
stages:
  - install
  - test
  - deploy

variables:
  PYTHON_VERSION: "3.12"

before_script:
  - apt-get update -y
  - apt-get install -y libpq-dev build-essential python3-dev
  - python3 -m venv venv
  - source venv/bin/activate
  - apt-get update -y
  - apt-get install -y libpq-dev
  - python --version
  - pip install --upgrade pip
  - pip install -v -r scrum-board-visi/requirements.txt

test:
  stage: test
  script:
    - echo "Running tests"
    - find . -name "test_*.py"  # Sprawdzi, czy pliki testowe są obecne
    - python scrum-board-visi/manage.py test  # Uruchomienie testów

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - master
