image: docker:20.10.16

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:20.10.16-dind  # Dodajemy Docker-in-Docker jako serwis, który umożliwi dostęp do Dockera w kontenerze

before_script:
  - apk add --no-cache --update python3 py3-pip docker  # Instalacja wymaganych pakietów
  - docker info  # Sprawdzamy, czy Docker działa
  - docker-compose --version  # Sprawdzamy wersję docker-compose

# Etap build - Budowanie obrazów Docker
build:
  stage: build
  script:
    - echo "Building Docker images"
    - docker-compose -f docker-compose.yml build  # Budowanie backendu i frontendu z pliku docker-compose.yml

# Etap test - Uruchomienie testów
test:
  stage: test
  script:
    - echo "Running tests"
    - docker-compose -f scrum-board-visi/docker-compose.yml run web python manage.py test  # Uruchomienie testów w kontenerze web (backend)

# Etap deploy - Wdrażanie na środowisko produkcyjne
deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    # Możesz dodać tu kod wdrożeniowy, np. deployment na serwer produkcyjny
  only:
    - master
