stages:
  - install
  - test
  - deploy

variables:
  # Określamy wersję Pythona
  PYTHON_VERSION: "3.12"

before_script:
  # Instalacja potrzebnych narzędzi
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt

install_dependencies:
  stage: install
  script:
    # Instalowanie zależności z requirements.txt
    - pip install -r requirements.txt

test:
  stage: test
  script:
    - |
      # Ustawienie SQLite na czas testów w pliku settings.py
      sed -i 's|\'ENGINE\':\'django.db.backends.postgresql\'|\'ENGINE\': \'django.db.backends.sqlite3\'|g' scrum-board-visi/settings.py
      # Uruchomienie migracji
      python manage.py makemigrations
      python manage.py migrate
      # Uruchomienie testów
      python manage.py test
  artifacts:
    paths:
      - test-reports/

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - master
