stages:
  - build
  - test
  - deploy

build_backend:
  stage: build
  script:
    - docker-compose build web


build_frontend:
  stage: build
  script:
    - docker-compose build frontend
  only:
    - main

test_backend:
  stage: test
  script:
    - docker-compose run web python manage.py test


test_frontend:
  stage: test
  script:
    - docker-compose run frontend npm run test


deploy:
  stage: deploy
  script:
    - echo "Deployment steps here"
