# Generated by Django 4.2.11 on 2024-04-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_rename_board_id_section_board'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section'),
        ),
    ]
